spring:
    jpa:
        defer-datasource-initialization: true
        open-in-view: true
    output:
        ansi:
            enabled: always
    application:
        name: "Sample App PRD"
server:
    port: 8080
    servlet:
        context-path: /Sample
