@host = http://localhost:8080/pessoas

{{host}}

###

POST {{host}}
Content-Type: application/json

{
    "nome"  : "Fulano",
    "idade" : 21 
}

###

GET {{host}}/1

###

PUT {{host}}/2
Content-Type: application/json

{
    "nome": "Mariazinha",
    "idade": 30
}

###

DELETE {{host}}/1